// flow-typed signature: b6d1bacef33640c5a972d5772a8ab526
// flow-typed version: <<STUB>>/react-loader-spinner_v^3.1.5/flow_v0.116.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-loader-spinner'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-loader-spinner' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-loader-spinner/dist' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/Audio' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/BallTriangle' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/Bars' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/Circles' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/CradleLoader' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/Grid' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/Hearts' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/MutatingDots' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/Oval' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/Plane' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/Puff' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/RevolvingDot' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/Rings' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/TailSpin' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/ThreeDots' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/Triangle' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/Watch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-loader-spinner/dist/index' {
  declare module.exports: $Exports<'react-loader-spinner/dist'>;
}
declare module 'react-loader-spinner/dist/index.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist'>;
}
declare module 'react-loader-spinner/dist/loader/Audio.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/Audio'>;
}
declare module 'react-loader-spinner/dist/loader/BallTriangle.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/BallTriangle'>;
}
declare module 'react-loader-spinner/dist/loader/Bars.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/Bars'>;
}
declare module 'react-loader-spinner/dist/loader/Circles.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/Circles'>;
}
declare module 'react-loader-spinner/dist/loader/CradleLoader.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/CradleLoader'>;
}
declare module 'react-loader-spinner/dist/loader/Grid.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/Grid'>;
}
declare module 'react-loader-spinner/dist/loader/Hearts.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/Hearts'>;
}
declare module 'react-loader-spinner/dist/loader/index' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader'>;
}
declare module 'react-loader-spinner/dist/loader/index.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader'>;
}
declare module 'react-loader-spinner/dist/loader/MutatingDots.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/MutatingDots'>;
}
declare module 'react-loader-spinner/dist/loader/Oval.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/Oval'>;
}
declare module 'react-loader-spinner/dist/loader/Plane.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/Plane'>;
}
declare module 'react-loader-spinner/dist/loader/Puff.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/Puff'>;
}
declare module 'react-loader-spinner/dist/loader/RevolvingDot.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/RevolvingDot'>;
}
declare module 'react-loader-spinner/dist/loader/Rings.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/Rings'>;
}
declare module 'react-loader-spinner/dist/loader/TailSpin.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/TailSpin'>;
}
declare module 'react-loader-spinner/dist/loader/ThreeDots.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/ThreeDots'>;
}
declare module 'react-loader-spinner/dist/loader/Triangle.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/Triangle'>;
}
declare module 'react-loader-spinner/dist/loader/Watch.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/Watch'>;
}
declare module 'react-loader-spinner/index' {
  declare module.exports: $Exports<'react-loader-spinner'>;
}
declare module 'react-loader-spinner/index.js' {
  declare module.exports: $Exports<'react-loader-spinner'>;
}
